<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <AssemblyVersion>1.1.26177.1</AssemblyVersion>
    <FileVersion>1.1.26177.1</FileVersion>
    <Version>$(VersionPrefix)1.1.26158.7$(VersionSuffix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Types\**" />
    <EmbeddedResource Remove="Types\**" />
    <None Remove="Types\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.2.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Org.Edgerunner.Mud.Common\Org.Edgerunner.Mud.Common.csproj" />
    <ProjectReference Include="..\Org.Edgerunner.Mud.Communication\Org.Edgerunner.Mud.Communication.csproj" />
  </ItemGroup>

</Project>
