<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <AssemblyVersion>1.0.26178.0</AssemblyVersion>
    <FileVersion>1.0.26178.0</FileVersion>
  </PropertyGroup>

</Project>
