<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <AssemblyVersion>1.0.26177.0</AssemblyVersion>
    <FileVersion>1.0.26177.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
