<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <AssemblyVersion>1.0.26178.2</AssemblyVersion>
    <FileVersion>1.0.26178.2</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Org.Edgerunner.Mud.Common\Org.Edgerunner.Mud.Common.csproj" />
  </ItemGroup>

</Project>
