; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Moo Udditor"
#define MyAppData "Edgerunner\Udditor"
#define MyAppVersion "1.2.26158"
#define MyAppPublisher "Thad Ryker (Dakkon/WiredWiz)"
#define MyAppURL "https://github.com/wiredwiz/Moo-Developer-Tools"
#define MyAppExeName "Moo Udditor.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C9192474-F5EE-410F-999B-6C56D646FAC2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesInstallIn64BitMode=x64
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=D:\Projects\Moo Developer Tools\LICENSE.txt
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Moo Udditor.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Antlr4.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\FastColoredTextBox.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\FastColoredTextBox.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\HtmlRenderer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\HtmlRenderer.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\JetBrains.Annotations.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Krypton.Docking.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Krypton.Navigator.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Krypton.Toolkit.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Krypton.Workspace.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Markdig.Signed.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Moo Udditor.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Moo Udditor.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Moo Udditor.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Moo Udditor.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Moo Udditor.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Moo.Editor.config"; DestDir: "{userappdata}\{#MyAppData}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Moo.Editor.Darkmode.Example.config"; DestDir: "{userappdata}\{#MyAppData}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\nlog.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\NLog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.ANTLR4.Tools.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.ANTLR4.Tools.Common.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Common.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Messaging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Messaging.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Moo.Editor.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Moo.Editor.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Moo.MooText.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Moo.MooText.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.MooSharp.Language.Grammar.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.MooSharp.Language.Grammar.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Mud.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Mud.Common.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Mud.Communication.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Mud.Communication.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Mud.MCP.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Org.Edgerunner.Mud.MCP.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net6.0-windows\Snippets.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
