; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Moo Udditor"
#define MyAppVersion "1.1.26178"
#define MyAppPublisher "Thad Ryker (Dakkon/WiredWiz)"
#define MyAppURL "https://github.com/wiredwiz/Moo-Developer-Tools"
#define MyAppExeName "Moo Udditor.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C9192474-F5EE-410F-999B-6C56D646FAC2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesInstallIn64BitMode=x64
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=D:\Projects\Moo Developer Tools\LICENSE.txt
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon={app}\Moo Udditor.exe
VersionInfoVersion=1.1.26178
VersionInfoCompany=Edgerunner
VersionInfoDescription=A Moo programming development environment
VersionInfoTextVersion=one point zero point two six one five eight
VersionInfoCopyright=Thaddeus Ryker 2024
VersionInfoProductName=Moo Udditor
VersionInfoProductVersion=1.1.26178
VersionInfoProductTextVersion=one point zero point two six one five eight

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Moo Udditor.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Antlr4.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\FastColoredTextBox.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\FastColoredTextBox.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\HtmlRenderer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\HtmlRenderer.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\JetBrains.Annotations.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Krypton.Docking.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Krypton.Navigator.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Krypton.Toolkit.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Krypton.Workspace.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Markdig.Signed.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Moo Udditor.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Moo Udditor.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Moo Udditor.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Moo Udditor.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Moo Udditor.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\nlog.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\NLog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.ANTLR4.Tools.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.ANTLR4.Tools.Common.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Common.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Messaging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Messaging.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Moo.Editor.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Moo.Editor.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Moo.MooText.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Moo.MooText.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.MooSharp.Language.Grammar.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.MooSharp.Language.Grammar.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Mud.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Mud.Common.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Mud.Communication.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Mud.Communication.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Mud.MCP.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Projects\Moo Developer Tools\Org.Edgerunner.Moo.Udditor\bin\Release\net8.0-windows\Org.Edgerunner.Mud.MCP.pdb"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  RemoveAppData: Boolean;

procedure AskRemoveAppData;
var
  Form: TSetupForm;
  IntroLabel: TNewStaticText;
  DataCheckBox: TNewCheckBox;
  OKButton: TNewButton;
begin
  RemoveAppData := False;

  Form := CreateCustomForm();
  try
    Form.Caption := 'Remove Application Data';
    Form.ClientWidth := ScaleX(420);
    Form.ClientHeight := ScaleY(150);
    Form.Position := poScreenCenter;

    IntroLabel := TNewStaticText.Create(Form);
    IntroLabel.Parent := Form;
    IntroLabel.Left := ScaleX(16);
    IntroLabel.Top := ScaleY(16);
    IntroLabel.Width := Form.ClientWidth - ScaleX(32);
    IntroLabel.AutoSize := False;
    IntroLabel.WordWrap := True;
    IntroLabel.Height := ScaleY(60);
    IntroLabel.Caption :=
      'Do you also want to remove your {#MyAppName} settings data ' +
      '(configuration, theme, snippets and saved worlds) for your user account?' + #13#10 + #13#10 +
      'This affects only your account, not other users on this computer.';

    DataCheckBox := TNewCheckBox.Create(Form);
    DataCheckBox.Parent := Form;
    DataCheckBox.Left := ScaleX(16);
    DataCheckBox.Top := ScaleY(88);
    DataCheckBox.Width := Form.ClientWidth - ScaleX(32);
    DataCheckBox.Caption := 'Delete my {#MyAppName} application data';
    DataCheckBox.Checked := False;

    OKButton := TNewButton.Create(Form);
    OKButton.Parent := Form;
    OKButton.Width := ScaleX(80);
    OKButton.Height := ScaleY(25);
    OKButton.Left := Form.ClientWidth - ScaleX(96);
    OKButton.Top := Form.ClientHeight - ScaleY(38);
    OKButton.Caption := 'OK';
    OKButton.ModalResult := mrOk;
    OKButton.Default := True;

    Form.ActiveControl := OKButton;

    if Form.ShowModal() = mrOk then
      RemoveAppData := DataCheckBox.Checked;
  finally
    Form.Free();
  end;
end;

function InitializeUninstall(): Boolean;
begin
  AskRemoveAppData();
  Result := True;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  AppDataPath: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    if RemoveAppData then
    begin
      AppDataPath := ExpandConstant('{userappdata}\{#MyAppName}');
      if (AppDataPath <> '') and
         (CompareText(ExtractFileName(AppDataPath), '{#MyAppName}') = 0) then
        DelTree(AppDataPath, True, True, True);
    end;
  end;
end;
